apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    components: seldon-core
    entity: online-model
  name: uncor2
  namespace: app-alpav
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: '2'
          - name: GUNICORN_THREADS
            value: '2'
          livenessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          name: uncor2
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          resources:
            limits:
              cpu: '2.0'
              memory: 2.0Gi
            requests:
              cpu: '2.0'
              memory: 2.0Gi
        serviceAccountName: default-editor
        terminationGracePeriodSeconds: 0
    graph:
      envSecretRefName: seldon-secret
      implementation: MLFLOW_SERVER
      modelUri: s3://app-alpav/0/de412bd934424c1f8c1686a33dcbc0ca/artifacts/model
      name: uncor2
    name: "31231aadfsdaf\u0430\u0444\u0432\u044B\u0430\u0444\u0432\u044B\u0430"
    replicas: 1
