apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    components: seldon-core
    entity: online-model
  name: uncor
  namespace: app-alpav
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: '2'
          - name: GUNICORN_THREADS
            value: '2'
          livenessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          name: uncor
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          resources:
            limits:
              cpu: '2.0'
              memory: 2.0Gi
            requests:
              cpu: '2.0'
              memory: 2.0Gi
        serviceAccountName: default-editor
        terminationGracePeriodSeconds: 0
    graph:
      envSecretRefName: seldon-secret
      implementation: MLFLOW_SERVER
      modelUri: s3://app-alpav/0/7bfd27cfaad94a6a8e17bcf04de2e31c/artifacts/model
      name: uncor
    name: "\u0412\u042B\u0410\u042B\u0412\u0410\u044B\u0432\u0430\u0444\u0432\u0430\
      1234?:\u2116&&#"
    replicas: 1
